# Generated by Django 4.0.1 on 2022-02-07 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExportConfigModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_FQAN', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='NodeGroupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceConfigModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('container', 'container'), ('compose', 'compose'), ('stack', 'stack')], editable=False, max_length=16, null=True)),
                ('host_name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceDeployPolicyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_manager_only', models.BooleanField(default=False)),
                ('is_work_only', models.BooleanField(default=False)),
                ('is_privilege', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceExportPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('only_apply_for_service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='docker_swarm_ez_core.serviceconfigmodel')),
            ],
        ),
        migrations.CreateModel(
            name='StackConfigModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceExportPolicyItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol', models.CharField(choices=[('udp', 'udp'), ('tcp', 'tcp'), ('http', 'http'), ('https', 'https')], max_length=6)),
                ('is_force_https', models.BooleanField(default=True)),
                ('port', models.IntegerField(default=-1)),
                ('inner_port', models.IntegerField(default=-1)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docker_swarm_ez_core.serviceexportpolicy')),
            ],
        ),
        migrations.AddField(
            model_name='serviceexportpolicy',
            name='only_apply_for_stack',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='docker_swarm_ez_core.stackconfigmodel'),
        ),
        migrations.AddField(
            model_name='serviceconfigmodel',
            name='deploy_policy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='docker_swarm_ez_core.servicedeploypolicymodel'),
        ),
        migrations.AddField(
            model_name='serviceconfigmodel',
            name='stack',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='docker_swarm_ez_core.stackconfigmodel'),
        ),
        migrations.CreateModel(
            name='NodeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=1000)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_set', to='docker_swarm_ez_core.nodegroupmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ImageExportModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.IntegerField()),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docker_swarm_ez_core.imagemodel')),
            ],
        ),
    ]
