# Generated by Django 4.0.1 on 2022-03-19 15:41

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnvNodeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='docker_swarm_ez_core.envnodemodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExportConfigModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_FQAN', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='NodeGroupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceConfigModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=100)),
                ('is_stateless', models.BooleanField(default=False)),
                ('image', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceDeployPolicyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_manager_only', models.BooleanField(default=False)),
                ('is_work_only', models.BooleanField(default=False)),
                ('is_privilege', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StackConfigModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('domain_name', models.CharField(help_text='一个域，其他服务部署在这个域中', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceExportPolicyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('only_apply_for_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='docker_swarm_ez_core.serviceconfigmodel')),
                ('only_apply_for_stack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='docker_swarm_ez_core.stackconfigmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceExportPolicyItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol', models.CharField(choices=[('udp', 'udp'), ('tcp', 'tcp'), ('http', 'http'), ('https', 'https')], max_length=6)),
                ('is_force_https', models.BooleanField(default=True)),
                ('sni_name', models.CharField(blank=True, default='', help_text='http/https only', max_length=100)),
                ('port', models.IntegerField(default=-1, help_text='udp/tcp only')),
                ('inner_port', models.IntegerField(default=-1)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docker_swarm_ez_core.serviceexportpolicymodel')),
            ],
        ),
        migrations.AddField(
            model_name='serviceconfigmodel',
            name='deploy_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='docker_swarm_ez_core.servicedeploypolicymodel'),
        ),
        migrations.AddField(
            model_name='serviceconfigmodel',
            name='stack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='docker_swarm_ez_core.stackconfigmodel'),
        ),
        migrations.CreateModel(
            name='NodeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(default='', max_length=64)),
                ('uuid', models.CharField(max_length=128, unique=True)),
                ('machine_id', models.CharField(max_length=254)),
                ('node_detail', models.JSONField(blank=True, null=True)),
                ('client_port', models.IntegerField(null=True)),
                ('client_addr', models.CharField(default='', max_length=254)),
                ('last_update_time', models.DateTimeField(null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_enable', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_set', to='docker_swarm_ez_core.nodegroupmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ImageExportModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.IntegerField()),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docker_swarm_ez_core.imagemodel')),
            ],
        ),
        migrations.CreateModel(
            name='EvnItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_security', models.BooleanField(default=False)),
                ('default_key', models.CharField(max_length=254)),
                ('value', models.CharField(max_length=254)),
                ('node', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='docker_swarm_ez_core.envnodemodel')),
            ],
        ),
    ]
