# Generated by Django 4.0.1 on 2022-03-19 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docker_swarm_ez_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceEnvConfigModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, help_text='值', max_length=254, null=True)),
                ('key', models.CharField(blank=True, help_text='使用新的名称', max_length=254, null=True)),
                ('env_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='docker_swarm_ez_core.evnitemmodel')),
            ],
        ),
        migrations.AddField(
            model_name='serviceconfigmodel',
            name='env_set',
            field=models.ManyToManyField(through='docker_swarm_ez_core.ServiceEnvConfigModel', to='docker_swarm_ez_core.EvnItemModel'),
        ),
        migrations.AddField(
            model_name='serviceenvconfigmodel',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docker_swarm_ez_core.serviceconfigmodel'),
        ),
    ]
