# Generated by Django 4.0.1 on 2022-02-07 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docker_swarm_ez_core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiceExportPolicy',
            new_name='ServiceExportPolicyModel',
        ),
        migrations.AlterField(
            model_name='serviceconfigmodel',
            name='deploy_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='docker_swarm_ez_core.servicedeploypolicymodel'),
        ),
        migrations.AlterField(
            model_name='serviceconfigmodel',
            name='service_type',
            field=models.CharField(blank=True, choices=[('container', 'container'), ('compose', 'compose'), ('stack', 'stack')], editable=False, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='serviceconfigmodel',
            name='stack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='docker_swarm_ez_core.stackconfigmodel'),
        ),
    ]
