# Generated by Django 4.0.1 on 2022-03-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docker_swarm_ez_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='work_dir',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='entrypoint',
            field=models.JSONField(),
        ),
    ]
