# Generated by Django 4.0.1 on 2022-02-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docker_swarm_ez_core', '0002_rename_serviceexportpolicy_serviceexportpolicymodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceexportpolicyitemmodel',
            name='sni_name',
            field=models.CharField(default='', help_text='http/https only', max_length=100),
        ),
        migrations.AlterField(
            model_name='serviceexportpolicyitemmodel',
            name='port',
            field=models.IntegerField(default=-1, help_text='udp/tcp only'),
        ),
    ]
