# Generated by Django 4.0.1 on 2022-03-20 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docker_swarm_ez_core', '0002_serviceenvconfigmodel_serviceconfigmodel_env_set_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeManagePointModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('swarm', 'swarm'), ('standalone', 'standalone')], max_length=32)),
                ('manage_id', models.CharField(blank=True, default='', help_text='swarm 就是集群id', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ServicePortConfigModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_image_cnf', models.BooleanField(default=False, editable=False)),
                ('inner_port', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='serviceexportpolicyitemmodel',
            name='inner_port',
        ),
        migrations.RemoveField(
            model_name='serviceexportpolicyitemmodel',
            name='policy',
        ),
        migrations.AddField(
            model_name='serviceconfigmodel',
            name='port_set',
            field=models.ManyToManyField(through='docker_swarm_ez_core.ServicePortConfigModel', to='docker_swarm_ez_core.ServiceExportPolicyItemModel'),
        ),
        migrations.AlterField(
            model_name='stackconfigmodel',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='ServiceExportPolicyModel',
        ),
        migrations.AddField(
            model_name='serviceportconfigmodel',
            name='export_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='docker_swarm_ez_core.serviceexportpolicyitemmodel'),
        ),
        migrations.AddField(
            model_name='serviceportconfigmodel',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docker_swarm_ez_core.serviceconfigmodel'),
        ),
        migrations.AddField(
            model_name='nodemodel',
            name='manage_point',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='docker_swarm_ez_core.nodemanagepointmodel'),
        ),
    ]
