# Generated by Django 4.0.1 on 2022-03-20 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docker_swarm_ez_core', '0003_nodemanagepointmodel_serviceportconfigmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceconfigmodel',
            name='service_id',
            field=models.CharField(default='', editable=False, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='serviceexportpolicyitemmodel',
            name='protocol',
            field=models.CharField(choices=[('udp', 'udp'), ('tcp', 'tcp'), ('tcp/udp', 'tcp/udp'), ('http', 'http'), ('https', 'https')], max_length=8),
        ),
    ]
