# Generated by Django 4.0.1 on 2022-03-20 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docker_swarm_ez_core', '0004_serviceconfigmodel_service_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceconfigmodel',
            name='cmds',
            field=models.TextField(blank=True, default='', help_text='一个命令一行,同Args'),
        ),
        migrations.AddField(
            model_name='serviceconfigmodel',
            name='entrypoint',
            field=models.TextField(blank=True, default='', help_text='入口'),
        ),
    ]
