# Generated by Django 4.0.1 on 2022-03-20 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docker_swarm_ez_core', '0005_serviceconfigmodel_cmds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stackconfigmodel',
            name='is_inner',
            field=models.BooleanField(default=False),
        ),
    ]
