# Generated by Django 4.0.1 on 2022-03-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docker_swarm_ez_core', '0006_stackconfigmodel_is_inner'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('net_addr', models.CharField(max_length=128)),
                ('type', models.CharField(choices=[('bridge', 'bridge'), ('overlay', 'overlay'), ('ipvlan', 'ipvlan'), ('macvlan', 'macvlan')], max_length=32)),
                ('enable_ipv6', models.BooleanField(default=False)),
                ('enable_encrypted', models.BooleanField(default=False, help_text='用于overlay模式, linux only')),
                ('attachable', models.BooleanField(default=False)),
            ],
        ),
    ]
