# Generated by Django 4.0.1 on 2022-03-23 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docker_swarm_ez_core', '0007_networkmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeLocalNetworkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceNetworkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='nodemodel',
            name='local_network_set',
            field=models.ManyToManyField(related_name='node_set', through='docker_swarm_ez_core.NodeLocalNetworkModel', to='docker_swarm_ez_core.NetworkModel'),
        ),
        migrations.AddField(
            model_name='serviceconfigmodel',
            name='network_set',
            field=models.ManyToManyField(through='docker_swarm_ez_core.ServiceNetworkModel', to='docker_swarm_ez_core.NetworkModel'),
        ),
        migrations.AlterField(
            model_name='networkmodel',
            name='net_addr',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='servicenetworkmodel',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docker_swarm_ez_core.networkmodel'),
        ),
        migrations.AddField(
            model_name='servicenetworkmodel',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docker_swarm_ez_core.serviceconfigmodel'),
        ),
        migrations.AddField(
            model_name='nodelocalnetworkmodel',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docker_swarm_ez_core.networkmodel'),
        ),
        migrations.AddField(
            model_name='nodelocalnetworkmodel',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docker_swarm_ez_core.nodemodel'),
        ),
    ]
